---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
     cloud: "{{ osp_cloud }}"
    register: openstack_info
  - name: Delete instances
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      state: absent
    loop: "{{ openstack_info.openstack_servers }}"
