==== Ansible Advanced Homework

This project provisions a QA and Prod Three-tier Application, serving a load-balnaced Apache Tomcat page, with CI/CD workflow on OPENTLC lab environments.

Instructions for use:

* Go to https://labs.opentlc.com/ and order two services:
  - OPENTLC Automation / Ansible Advanced - Homework
  - OPENTLC Automation / Ansible Advanced - OpenStack
* When the provisioning emails arrive, make a note of the GUID for each. They will be needed later.
* When the Homework envrionment is ready, log into your bastion host using your OPENTLC private key, and become the `root` user
[source,text]
----
[laptop ~]$ export TOWER_GUID=<Ansible Homework GUID from email>
[laptop ~]$ export MYKEY=<~/.ssh/your_opentlc_key.pem>
[laptop ~]$ export MYUSER=<username-company.com>
[laptop ~]$ ssh -i ${MYKEY} ${MYUSER}@bastion.${TOWER_GUID}.example.opentlc.com
[bastion ~]$ sudo -i
[bastion ~]#
----
* Copy your OPENTLC private key into a file on your bastion host `/root/.ssh/mykey.pem`, and ensure its ownership and mode are appropriate (owner `root:root`, mode `0400`)
[source,text]
----
[bastion ~]# ls -l /root/.ssh/mykey.pem
-r--------. 1 root root 90 Mar  5 19:13 /root/.ssh/mykey.pem
----
* Clone this repository into `/root` on the bastion host and change into the cloned directory
[source,text]
----
[bastion ~]# pwd
/root
[bastion ~]# git clone https://github.com/zjpeterson/ansible_advance_homework.git
Cloning into 'ansible_advance_homework'...
remote: Enumerating objects: 583, done.
remote: Total 583 (delta 0), reused 0 (delta 0), pack-reused 583
Receiving objects: 100% (583/583), 71.69 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (257/257), done.
[bastion ~]# cd ansible_advance_homework
----
* Set up the OpenStack environment by executing the `site-setup-workstation.yml` playbook, specifying extra vars as shown below:
[source,text]
----
[bastion]# OSP_GUID=<OpenStack GUID from mail>
[bastion]# ansible-playbook site-setup-workstation.yml -e OSP_GUID=${OSP_GUID} --private-key=/root/.ssh/mykey.pem -u <username-company.com>
----
* Set up the Ansible Tower environment by executing the `site-config-tower.yml` playbook, specifying extra vars as shown below:
[source,text]
----
[bastion]# TOWER_GUID=<Ansible Tower Homework GUID from mail>
[bastion]# OSP_GUID=<Openstack for Ansible GUID from mail>
[bastion]# OPENTLC_LOGIN=<username-company.com>
[bastion]# OPENTLC_PASSWORD=<your openlc account password>
[bastion]# GITHUB_REPO=https://github.com/<githubhandler>/ansible_advance_homework
[bastion]# JQ_REPO_BASE=http://www.opentlc.com/download/ansible_bootcamp
[bastion]# REGION=<enter region name example us-east-1>
[bastion]# RH_MAIL_ID=<your mail id for dynamic inventory tag>
[bastion]# ansible-playbook site-config-tower.yml -e tower_GUID=${TOWER_GUID} -e osp_GUID=${OSP_GUID} -e opentlc_login=${OPENTLC_LOGIN} -e path_to_opentlc_key=/root/.ssh/mykey.pem -e param_repo_base=${JQ_REPO_BASE} -e opentlc_password=${OPENTLC_PASSWORD} -e REGION_NAME=${REGION} -e EMAIL=${RH_MAIL_ID} -e github_repo=${GITHUB_REPO}
----


.List of Playbooks
[%header,cols=2*]
|===
| File | Purpose
| app-tier | Install application server role
| db-tier  | Install postgressql server for database role
| lb-tier  | Install HA proxy role
| base-config | Setup yum repo and base packages role
| setup-workstation | Setup workstation, create network, ssh keypair, security group etc. role 
| osp-servers | Provision OSP Instances role
| osp-instance-delete | Delete OSP Instances role
| osp-facts | Genrate in-memory inventory for OSP instances role
| roles/config-tower/vars/main.yml | Very important file to review. All the variable values are set there. Please do not make any changes in the file
| config-tower | Role to configure ansible tower job templates and workflow
| aws_creds.yml | Fetch GUIDkey.pem from bastion of Three tier application env and create machine credential to connect to AWS instances
| aws_provision.yml | Use `order_svc.sh` script to provision env
| aws_status_check.yml | Check aws instances are up or not
| site-3tier-app.yml | Playbook to deploy three tier app
| site-install-isolated-node.yml | Playbook to install isolated node
| site-config-tower.yml | Playbook to call role `config-tower`
| site-osp-delete.yml | Playbook to call role
| site-osp-instances.yml | Playbook to call role
| site-setup-workstation.yml | Playbook to call role
| site-smoke-osp.yml | Playbook to test three tier app on OSP
| site-smoketest-aws.yml | Playbook to test three tier app on AWS
| grading-script.yml | Self grading script
| roles/config-tower/tasks/ec2_dynamic.yml | For creating Dynamic inventory in Ansible tower. Use `AWS Access Key` for credential
| roles/config-tower/tasks/job_template.yml | For creating job templates
| roles/config-tower/tasks/pre-config-tower.yml | Any pre config tasks needed
| roles/config-tower/tasks/workflow_template.yml | genrate workflow from `workflow.yml` file
| roles/config-tower/tasks/post-config-tower.yml | any post config jobs
|===
A similar table of roles can be found in the README under `roles/`