- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation
       ansible_user: "{{ opentlc_login }}"
       ansible_ssh_private_key_file: ~/.ssh/mykey.pem

- hosts: workstation
  become: yes
  roles:
    - osp-servers
