- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - name: Check website
    uri:
      url: "http://{{ item.public_v4 }}"
      return_content: yes
    loop: "{{ openstack_info.openstack_servers }}"
    register: webpage
    tags:
      - osp.smoke
    failed_when: "'Ansible has done its job' not in webpage.results[0].content"
