---
# tasks file for lb-tier
- name: install packages
  yum:
    name: haproxy
    state: latest
- name: enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg }}"
  notify: restart HAproxy
