---
# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      groups:
      - "{{ item.metadata.group }}"
      - "{{ item.metadata.deployment_name }}"
      # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      # ansible_ssh_user: cloud-user
     loop: "{{ result.ansible_facts.openstack_servers }}"
