---
# tasks file for app-tier
- name: install tomcat
  yum:
    name: tomcat
    state: latest

- name: create tomcat root directory
  file:
    path: "{{ tomcat_root }}"
    state: directory

- name: copy templated index.html to apache root
  template:
    src: index.html.j2
    dest: "{{ tomcat_root }}/index.html"
    mode: 0644

- name: start and enable tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
