---
# tasks file for base-config
- name: Install repo file
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
    dest: /etc/yum.repos.d/internal.repo
  # don't apply this step to EC2 instances
  when: "'ec2' not in group_names"